rsync error

diff --git a/source/RAM-DISK-Dockerlog/usr/local/emhttp/plugins/RAM-DISK-Dockerlog/event/starting b/source/RAM-DISK-Dockerlog/usr/local/emhttp/plugins/RAM-DISK-Dockerlog/event/starting
--- a/source/RAM-DISK-Dockerlog/usr/local/emhttp/plugins/RAM-DISK-Dockerlog/event/starting
+++ b/source/RAM-DISK-Dockerlog/usr/local/emhttp/plugins/RAM-DISK-Dockerlog/event/starting
@@ -7,6 +7,23 @@ if grep -q 'nohup $UNSHARE --propagation slave -- $DOCKER' /etc/rc.d/rc.docker &
     #Protection check for possible meddling via go file
     if ! grep -q "rsync" /etc/rc.d/rc.docker; then
         
+        #Check version for rsync changes
+        source /etc/unraid-version
+        if [[ "$version" == "7.3.3" ]] || [[ "$(printf '%s\n' "$version" "$required" | sort -V | tail -n1)" == "$version" ]]; then
+        sed -i '/nohup $UNSHARE --propagation slave -- $DOCKER/i \
+         # move json/logs to RAM-Disk\
+         rsync -aH --delete --insecure-links /var/lib/docker/containers/ ${DOCKER_APP_CONFIG_PATH%/}/containers_backup\
+         mountpoint -q /var/lib/docker/containers || mount -t tmpfs tmpfs /var/lib/docker/containers || { logger -t docker Error: RAM-Disk could not be mounted! && /usr/local/emhttp/plugins/dynamix/scripts/notify -e "RAM-DISK-Dockerlog" -s "Error: RAM-Disk could not be mounted!" -i alert; }\
+         rsync -aH --delete --insecure-links ${DOCKER_APP_CONFIG_PATH%/}/containers_backup/ /var/lib/docker/containers\
+         logger -t docker RAM-Disk created' /etc/rc.d/rc.docker
+
+        sed -i '/tear down the bridge/i \
+         # backup json/logs and remove RAM-Disk\
+         rsync -aH --delete --insecure-links /var/lib/docker/containers/ ${DOCKER_APP_CONFIG_PATH%/}/containers_backup\
+         umount /var/lib/docker/containers || { logger -t docker Error: RAM-Disk could not be unmounted! && /usr/local/emhttp/plugins/dynamix/scripts/notify -e "RAM-DISK-Dockerlog" -s "Error: RAM-Disk could not be unmounted!" -i alert; }\
+         rsync -aH --delete --insecure-links ${DOCKER_APP_CONFIG_PATH%/}/containers_backup/ /var/lib/docker/containers\
+         logger -t docker RAM-Disk removed' /etc/rc.d/rc.docker
+        else
         sed -i '/nohup $UNSHARE --propagation slave -- $DOCKER/i \
          # move json/logs to RAM-Disk\
          rsync -aH --delete /var/lib/docker/containers/ ${DOCKER_APP_CONFIG_PATH%/}/containers_backup\
@@ -20,6 +37,7 @@ if grep -q 'nohup $UNSHARE --propagation slave -- $DOCKER' /etc/rc.d/rc.docker &
          umount /var/lib/docker/containers || { logger -t docker Error: RAM-Disk could not be unmounted! && /usr/local/emhttp/plugins/dynamix/scripts/notify -e "RAM-DISK-Dockerlog" -s "Error: RAM-Disk could not be unmounted!" -i alert; }\
          rsync -aH --delete ${DOCKER_APP_CONFIG_PATH%/}/containers_backup/ /var/lib/docker/containers\
          logger -t docker RAM-Disk removed' /etc/rc.d/rc.docker
+        fi
 
 
         #load and set backup interval
