2025.02.14

diff --git a/source/RAM-DISK-Dockerlog/usr/local/emhttp/plugins/RAM-DISK-Dockerlog/event/starting b/source/RAM-DISK-Dockerlog/usr/local/emhttp/plugins/RAM-DISK-Dockerlog/event/starting
--- a/source/RAM-DISK-Dockerlog/usr/local/emhttp/plugins/RAM-DISK-Dockerlog/event/starting
+++ b/source/RAM-DISK-Dockerlog/usr/local/emhttp/plugins/RAM-DISK-Dockerlog/event/starting
@@ -1,16 +1,58 @@
-#!/bin/bash
-source /etc/unraid-version
+# Check if we already modified the rc.docker
+if [[ ! -f /tmp/RAM-DISK-Dockerlog/modified ]]; then
 
-if [[ ! -f /tmp/RAM-DISK-Dockerlog/modified ]] && [[ -f /boot/config/plugins/RAM-DISK-Dockerlog/settings.cfg ]]; then
+# Make absolutely sure we can modify the file savely!
+if grep -q 'nohup $UNSHARE --propagation slave -- $DOCKER' /etc/rc.d/rc.docker && grep -q "tear down the bridge" /etc/rc.d/rc.docker; then
 
-    if [[ -f /usr/local/emhttp/plugins/RAM-DISK-Dockerlog/script/$version ]]; then
+    #Protection check for possible meddling via go file
+    if ! grep -q "rsync" /etc/rc.d/rc.docker; then
+        
+        sed -i '/nohup $UNSHARE --propagation slave -- $DOCKER/i \
+         # move json/logs to RAM-Disk\
+         rsync -aH --delete /var/lib/docker/containers/ ${DOCKER_APP_CONFIG_PATH%/}/containers_backup\
+         mountpoint -q /var/lib/docker/containers || mount -t tmpfs tmpfs /var/lib/docker/containers || logger -t docker Error: RAM-Disk could not be mounted!\
+         rsync -aH --delete ${DOCKER_APP_CONFIG_PATH%/}/containers_backup/ /var/lib/docker/containers\
+         logger -t docker RAM-Disk created' /etc/rc.d/rc.docker
+
+        sed -i '/tear down the bridge/i \
+         # backup json/logs and remove RAM-Disk\
+         rsync -aH --delete /var/lib/docker/containers/ ${DOCKER_APP_CONFIG_PATH%/}/containers_backup\
+         umount /var/lib/docker/containers || logger -t docker Error: RAM-Disk could not be unmounted!\
+         rsync -aH --delete ${DOCKER_APP_CONFIG_PATH%/}/containers_backup/ /var/lib/docker/containers\
+         logger -t docker RAM-Disk removed' /etc/rc.d/rc.docker
+
+
+        #load and set backup interval
         interval=$(cat /boot/config/plugins/RAM-DISK-Dockerlog/settings.cfg)
-        source /usr/local/emhttp/plugins/RAM-DISK-Dockerlog/script/$version
-        
-    else
-    
-        logger -t RAM-DISK-Dockerlog "Warning, no modification for $version found"
-        
-    fi
 
+          echo '<?php
+          $sync_interval_minutes='${interval}';
+          if ( ! ((date("i") * date("H") * 60 + date("i")) % $sync_interval_minutes) && file_exists("/var/lib/docker/containers")) {
+            exec("
+              [[ ! -d /var/lib/docker_bind ]] && mkdir /var/lib/docker_bind
+              if ! mountpoint -q /var/lib/docker_bind; then
+                if ! mount --bind /var/lib/docker /var/lib/docker_bind; then
+                  logger -t docker Error: RAM-Disk bind mount failed!
+                fi
+              fi
+              if mountpoint -q /var/lib/docker_bind; then
+                rsync -aH --delete /var/lib/docker/containers/ /var/lib/docker_bind/containers && logger -t docker Success: Backup of RAM-Disk created.
+                umount -l /var/lib/docker_bind
+              else
+                logger -t docker Error: RAM-Disk bind mount failed!
+              fi
+            ");
+          }' > /tmp/RAM-DISK-Dockerlog/monitor
+  
+        if [[ $interval != 0 ]]; then
+          sed -i "/^<?PHP$/a include_once('/tmp/RAM-DISK-Dockerlog/monitor');" /usr/local/emhttp/plugins/dynamix/scripts/monitor
+        fi
+        echo $version > /tmp/RAM-DISK-Dockerlog/modified
+
+    else
+        logger -t RAM-DISK-Dockerlog "Error: rc.docker is modified, possibly by the go file"
+    fi
+else
+    logger -t RAM-DISK-Dockerlog "Error: rc.docker incompatible!"
+fi
 fi
